config/routes.rb
Rails.application.routes.draw do

  resources :drills, :plays

  resources :users, only: [:new, :create]

  get 'about' => 'welcome#about'

  get 'contact' => 'welcome#contact'

  root 'welcome#index'

end

app/models/drill.rb
class Drill < ActiveRecord::Base
  has_attached_file :file
  do_not_validate_attachment_file_type :file
end

app/models/play.rb
class Play < ActiveRecord::Base
  has_attached_file :document
  do_not_validate_attachment_file_type :document
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase if email.present? }
  validates :name, length: { minimum: 1, maximum: 100 }, presence: true
  validates :password, presence: true, length: { minimum: 6 }, unless: :password_digest
  validates :password, length: { minimum: 6 }, allow_blank: true
  validates :email,
            presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 254 }

# #6
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/drills_controller.rb
class DrillsController < ApplicationController
  def index
    @drills = Drill.all
  end

  def show
    @drill = Drill.find(params[:id])
  end

  def new
    @drill  = Drill.new
  end

  def create
    @drill = Drill.new(drill_params)

    if @drill.save
      flash[:notice] = "You successfully created a new drill."
      redirect_to @drill
    else
      flash.now[:alert] = "There was a problem uploading your drill. Please try again."
      render :new
    end
  end

  def edit
    @drill = Drill.find(params[:id])
  end

  def update
     @drill = Drill.find(params[:id])
     @drill.assign_attributes(drill_params)

     if @drill.save
       flash[:notice] = "Drill was updated successfully."
       redirect_to @drill
     else
       flash.now[:alert] = "There was a problem the drill. Please try again."
       render :edit
     end
   end

   def destroy
     @drill = Drill.find(params[:id])

     if @drill.destroy
       flash[:notice] = "\"#{@drill.title}\" was deleted successfully."
       redirect_to drills_path
     else
       flash.now[:alert] = "There was a problem deleting the drill."
       render :show
     end
   end

   private

   def drill_params
     params.require(:drill).permit(:title, :description, :file)
   end

end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController
  def index
    @plays = Play.all
  end

  def show
    @play = Play.find(params[:id])
  end

  def new
    @play = Play.new
  end

  def create
    @play = Play.new(play_params)

    if @play.save
      flash[:notice] = "Your play was successfully uploaded."
      redirect_to @play
    else
      flash.now[:alert] = "There was a problem uploading your play. Please try again."
      render :new
    end
  end

  def edit
    @play = Play.find(params[:id])
  end

  def update
    @play = Play.find(params[:id])
    @play.assign_attributes(play_params)

    if @play.save
      flash[:notice] = "You have updated your '#{@play.title}' play."
      redirect_to @play
    else
      flash.now[:alert] = "There was a problem updating your play. Please try again."
      render :edit
    end
  end

  def destroy
    @play = Play.find(params[:id])

    if @play.delete
      flash[:notice] = "You successfully deleted your play."
      redirect_to plays_path
    else
      flash.now[:alert] = "There was a problem deleting your play."
      render :show
    end
  end

  private

  def play_params
    params.require(:play).permit(:title, :description, :document)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new
    @user.name = params[:user][:name]
    @user.email = params[:user][:email]
    @user.password = params[:user][:password]
    @user.password_confirmation = params[:user][:password_confirmation]

    if @user.save
      flash[:notice] = "Welcome #{@user.name}!"
      redirect_to root_path
    else
      flash.now[:alert] = "There was an error creating your account. Please try again."
      render :new
    end 
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def form_group_tag(errors, &block)
     css_class = 'form-group'
     css_class << ' has-error' if errors.any?
# #5
     content_tag :div, capture(&block), class: css_class
   end
end

app/helpers/drills_helper.rb
module DrillsHelper
end

app/helpers/plays_helper.rb
module PlaysHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/drills/_form.html.erb
<%= form_for @drill, html: { multipart: true } do |f| %>
   <%= f.label :file %>
   <%= f.file_field :file %>

   <%= f.label :title %>
   <%= f.text_field :title %>

   <%= f.label :description %>
   <%= f.text_area :description %>

   <%= f.submit "Save" %>
 <% end %>

app/views/drills/edit.html.erb
<h1>Drills#edit</h1>
<p>Find me in app/views/drills/edit.html.erb</p>
<%= render partial: 'form', locals: {drill: @drill} %>

app/views/drills/index.html.erb
<h1>Drills</h1>
<%= link_to "Create new Drill", new_drill_path, class: 'btn btn-success' %>
  <% @drills.each do |drill| %>
  <p><%= link_to drill.title, drill_path(drill.id) %></p>
  <% end %>

app/views/drills/new.html.erb
<h3>Create new Drill</h3>
<%= render partial: 'form', local: {drill: @drill} %>

app/views/drills/show.html.erb
<h1>Drills#show</h1>
<%= link_to "Edit", edit_drill_path(@drill), class: 'btn btn-success' %>
<%= link_to "Delete Drill", @drill, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this drill?'} %>
<h1><%= @drill.title %></h1>
 <p><%= @drill.description %></p>
 <%= link_to "File", @drill.file.url %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Basketball</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="stylessheets/normalize.css">
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Open+Sans:400,800,600,700,300">
  <link rel="stylesheet" type="text/css" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div> <!-- nav bar -->
    <nav class="navbar">
      <ul class="nav-list">
        <li class="nav-items">
          <%= link_to "Home", root_path, class: 'nav-links' %>
        </li>
        <li class="nav-items">
          <%= link_to "Drills", drills_path, class: 'nav-links' %>
        </li>
        <li class="nav-items">
          <%= link_to "Plays", plays_path, class: 'nav-links' %>
        </li>
        <li class="nav-items">
          <%= link_to "About", about_path, class: 'nav-links' %>
        </li>
        <li class="nav-items">
          <%= link_to "Contact", contact_path, class: 'nav-links' %>
        </li>
      </ul>
    </nav>
  </div>

  <% if flash[:notice] %>
       <div class="alert alert-success">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:notice] %>
       </div>
     <% elsif flash.now[:alert] %>
       <div class="alert alert-danger">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash.now[:alert] %>
       </div>
     <% elsif flash[:alert] %>
       <div class="alert alert-warning">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:alert] %>
       </div>
     <% end %>





<%= yield %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/plays/_form.html.erb
<%= form_for @play, html: { multipart: true } do |f| %>
  <%= f.label :document%>
  <%= f.file_field :document %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.submit "Update" %>
<% end %>

app/views/plays/edit.html.erb
<h1>Plays#edit</h1>
<p>Find me in app/views/plays/edit.html.erb</p>
<%= render partial: 'form', locals: {play: @play} %>

app/views/plays/index.html.erb
<h1>Plays</h1>
<%= link_to "Create new Play", new_play_path, class: 'btn btn-success' %>
  <% @plays.each do |play| %>
  <p><%= link_to play.title, play_path(play.id) %></p>
  <% end %>

app/views/plays/new.html.erb
<h3>Create new Play</h3>
<%= render partial: 'form', locals: {play: @play} %>

app/views/plays/show.html.erb
<h1>Plays#show</h1>
<p>Find me in app/views/plays/show.html.erb</p>
<%= link_to "Edit", edit_play_path %>
<%= link_to "Delete", @play, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this drill?'} %>

<h3><%= @play.title %></h3>
<p><%= @play.description %></p>
<%= link_to "Document", @play.document.url %>

app/views/users/new.html.erb
<h2>Sign up</h2>

 <div class="row">
   <div class="col-md-8">
     <%= form_for @user do |f| %>
       <% if @user.errors.any? %>
         <div class="alert alert-danger">
           <h4><%= pluralize(@user.errors.count, "error") %>.</h4>
           <ul>
             <% @user.errors.full_messages.each do |msg| %>
               <li><%= msg %></li>
             <% end %>
           </ul>
         </div>
       <% end %>
       <%= form_group_tag (@user.errors[:name]) do %>
         <%= f.label :name %>
         <%= f.text_field :name, autofocus: true, class: 'form-control', placeholder: "Enter name" %>
       <% end %>
       <%= form_group_tag(@user.errors[:email]) do %>
         <%= f.label :email %>
         <%= f.email_field :email, class: 'form-control', placeholder: "Enter email" %>
       <% end %>
       <%= form_group_tag(@user.errors[:password]) do %>
         <%= f.label :password %>
         <%= f.password_field :password, class: 'form-control', placeholder: "Enter password" %>
       <% end %>
       <%= form_group_tag(@user.errors[:password_confirmation]) do %>
         <%= f.label :password_confirmation %>
         <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "Enter password confirmation" %>
       <% end %>
       <div class="form-group">
         <%= f.submit "Sign up", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/welcome/about.html.erb
<div>
  <h1>About</h1>
</div>

app/views/welcome/contact.html.erb
<div>
  <h1>Contact</h1>
</div>

app/views/welcome/index.html.erb
<div class="container">
  <h1>Welcome#index</h1>
    <p>Find me in app/views/welcome/index.html.erb</p>
    <%= link_to "Sign Up", new_user_path, class: 'btn btn-primary' %>
</div>